version: "3"
services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh docker_dev_start.sh
    expose:
      - 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
  db:
    restart: always
    image: postgres:11-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    # volumes:
    #  - pgdata:/var/lib/postgresql/data'
    # volumes:
    # pgdata:
